# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: h5shop

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      # Run Prettier to check formatting
      - name: Check Prettier formatting
        run: npx prettier --check "**/*.{js,ts,tsx,jsx,json,css,scss}"

      # Run ESLint to check code quality
      - name: Lint with ESLint
        run: npx eslint "**/*.{js,ts,tsx,jsx}"